module PEClient
  class Client
    attr_reader api_key: String
    attr_reader base_url: URI
    attr_reader connection: Faraday::Connection

    @provisioning_block: (^(Faraday::Connection) -> void)?
    def initialize: (api_key: String, base_url: String | URI, ca_file: String) ?{ (Faraday::Connection) -> void } -> void
    def deep_dup: () -> Client
    def get: (String, ?body: Hash[String | Symbol, untyped], ?params: Hash[String | Symbol, String | Integer], ?headers: Hash[String | Symbol, String]) -> (Hash[String, untyped] | Array[untyped] | String)
    def post: (String, ?body: Hash[String | Symbol, untyped], ?params: Hash[String | Symbol, String | Integer], ?headers: Hash[String | Symbol, String]) -> (Hash[String, untyped] | Array[untyped] | String)
    def put: (String, ?body: Hash[String | Symbol, untyped], ?params: Hash[String | Symbol, String | Integer], ?headers: Hash[String | Symbol, String]) -> (Hash[String, untyped] | Array[untyped] | String)
    def delete: (String, ?body: Hash[String | Symbol, untyped]?, ?params: Hash[String | Symbol, String | Integer], ?headers: Hash[String | Symbol, untyped]) -> (Hash[String, untyped] | Array[untyped] | String)

    # Resources
    @node_inventory_v1: Resource::NodeInventoryV1
    def node_inventory_v1: () -> Resource::NodeInventoryV1
    @rbac_v1: Resource::RBACV1
    def rbac_v1: () -> Resource::RBACV1
    @rbac_v2: Resource::RBACV2
    def rbac_v2: () -> Resource::RBACV2
    @node_classifier_v1: Resource::NodeClassifierV1
    def node_classifier_v1: -> Resource::NodeClassifierV1
    @orchestrator_v1: Resource::OrchestratorV1
    def orchestrator_v1: -> Resource::OrchestratorV1
    @code_manager_v1: Resource::CodeManagerV1
    def code_manager_v1: -> Resource::CodeManagerV1
    @status_v1: Resource::StatusV1
    def status_v1: -> Resource::StatusV1
    @activity_v1: Resource::ActivityV1
    def activity_v1: -> Resource::ActivityV1
    @activity_v2: Resource::ActivityV2
    def activity_v2: -> Resource::ActivityV2
    @metrics_v1: Resource::MetricsV1
    def metrics_v1: -> Resource::MetricsV1
    @metrics_v2: Resource::MetricsV2
    def metrics_v2: -> Resource::MetricsV2
    @puppet_admin_v1: Resource::PuppetAdminV1
    def puppet_admin_v1: -> Resource::PuppetAdminV1
    @puppet_server_v3: Resource::PuppetServerV3
    def puppet_server_v3: -> Resource::PuppetServerV3

    # Private methods
    def handle_response: (Faraday::Response) -> (Hash[String, untyped] | Array[untyped] | String)
  end
end
