module PEClient
  module Resource
    class NodeClassifierV1
      class ImportHierarchy < Base
        BASE_PATH: String

        def replace: (Array[Hash[Symbol | String, untyped]]) -> Hash[String, untyped]
      end
    end
  end
end
