module PEClient
  module Resource
    class NodeClassifierV1
      class Nodes < Base
        BASE_PATH: String

        def get: (?node: String?, ?limit: Integer?, ?offset: Integer?) -> Hash[String, untyped]
      end
    end
  end
end
