module PEClient
  module Resource
    class RBACV1
      class Passwords < Base
        def generate_reset_token: (String) -> Hash[String, untyped]
        def reset: (String, String) -> Hash[String, untyped]
        def change: (String, String) -> Hash[String, untyped]
        def validate_password: (String, ?reset_token: String?) -> Hash[String, untyped]
        def validate_login: (String) -> Hash[String, untyped]
      end
    end
  end
end
