name: "release prep"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of gem to be released."
        required: true

jobs:
  release_prep:
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_release_prep.yml@main"
    with:
      target: "main"
      version: "${{ github.event.inputs.version }}"
    secrets: "inherit"
